### ISSUE TITLE
Incorrect hidden name attribute input provided by the example template

### ISSUE THREAD

**Issue by patrick3Dgroup** [craftcms/commerce-stripe#220]
### Description

Following the example template causes an error with a message - 'Invalid payment or order. Please review.". Using 'gateway.getPaymentFormHtml()' works fine but when you follow the example template to create your own custom form, you will encounter an error. 

I solved the issue by passing in 'paymentForm[stripe][paymentMethodId]' as the hidden input name attribute instead of what the example gave.

### Steps to reproduce

1. Install Commerce and Commerce Stripe, set up Payment Intents 
2. Submit a cart purchase using the example template 

### Additional info

- Craft CMS version: 4.1.2
- Stripe for Craft Commerce version: 3.0.1
- PHP version: 8.1.10
- Database driver & version: MySQL 8.0.21
- Plugins & versions:

**Comment by bleepsandblops** [comment]
Thanks for this, really helped me!

**Comment by nfourtythree** [comment]
Hi @patrick3Dgroup 

Thank you for raising this. We have updated the README to reflect the current best practices when it comes to creating a payment form.

As of Commerce 4, payment forms are all namespaced by the gateway's handle this is detailed in the upgrade guide: https://craftcms.com/docs/commerce/4.x/upgrading.html#payment-forms

Hopefully, the update to the plugin's README will avoid confusion in the future.

Thanks!

**Comment by tigerchick** [comment]
> Hi @patrick3Dgroup
> 
> Thank you for raising this. We have updated the README to reflect the current best practices when it comes to creating a payment form.
> 
> As of Commerce 4, payment forms are all namespaced by the gateway's handle this is detailed in the upgrade guide: https://craftcms.com/docs/commerce/4.x/upgrading.html#payment-forms
> 
> Hopefully, the update to the plugin's README will avoid confusion in the future.
> 
> Thanks!

Hi, apologies if I've missed something but there still seems to be the incorrect line of code in the readme:

`hiddenInput.setAttribute('name', 'paymentMethodId'); // Craft Commerce only needs this`

Just wasted a couple of hours on this and eventually came across this issue in the closed pile. Like I say, apologies if I got the wrong end of the stick somehow, I just want anyone else to be thrown by this.

**Comment by chrisdaviesweb** [comment]
Just had the same issue. Took 3 hours of searching around to find this. 'https://github.com/craftcms/commerce-stripe' is still showing the incorrect code for paymentMethodId.

**Comment by stevecomrie** [comment]
Yeah, this issue is definitely not closed. This is a glaring error in the sample documentation and is next to impossible to debug. @nfourtythree

**Comment by gaelpleeroy** [comment]
@nfourtythree Can you reopen the issue please? The readme is still not updated with that fix.

**Comment by hatyi** [comment]
Can confirm I've ran into this issue as well yesterday.
