### ISSUE TITLE
chargeInvoicesImmediately not working

### ISSUE THREAD

**Issue by bymayo** [craftcms/commerce-stripe#66]
We've recently moved one of our clients over to Payment Intents instead of Charge in prep for SCA! 

But we noticed that when making the change that payments go through to Stripe, but only an invoice is created and the redirect param doesn't kick in (Which Im guessing is because payment isn't made). We're also never redirected to the 3D secure page to capture the payment.

In Stripe I can see that the subscription has been attempted as an invoice is created and I can open the Payment Page (E.g. https://pay.stripe.com/invoice/invst_jOotdtS1UnWt3OaPceaKKsQKWX) and then manually capture the payment.

I noticed the setting:

```
<?php
return [
   'chargeInvoicesImmediately' => true
];
```

And thought this might make the invoice automatically charge, but putting this inside `config/commerce-stripe.php` has no difference to it only generating an invoice.

**Comment by andris-sevcenko** [comment]
3DS cards don't really work with subscriptions yet, as that requires adding support for Setup Intents and, well, nobody has gotten around to that yet..

**Comment by bymayo** [comment]
@andris-sevcenko So is this likely to be implemented within this plugin, or are you saying it's not available on Stripe yet?

**Comment by andris-sevcenko** [comment]
This is possible with Stripe, but not this plugin. Mainly because we have to figure out a solution for cards requiring mid-subscription and how to deal with that (contacting the cardholder and the like)

Until we do that, allowing to start subscriptions with 3DS enabled cards is a bit recklesa.

**Comment by bymayo** [comment]
@andris-sevcenko No problem, I understand it's a lot of work. My only main concern is if this affects SCA, and if it would be available before the Sept cut-off?

**Comment by andris-sevcenko** [comment]
The current working plan is to have it working before September cut-off.

**Comment by andris-sevcenko** [comment]
And by "working plan" I don't mean "we'll see", but I mean "we have a plan and we are working on it" :)

**Comment by bymayo** [comment]
Sounds good to me! I'll check back in a month or so then! 💯

**Comment by andris-sevcenko** [comment]
@bymayo Once Commerce 3 alpha 2 is out, this should be achievable with https://github.com/craftcms/commerce-stripe/tree/feature-3ds-subscriptions

That's without Setup Intents, though, so will likely interrupt the subscription every billing cycle to re-verify using 3ds. That's still on the list.

**Comment by bymayo** [comment]
Okay, I'm sure we can work with that for now though, as our subscription payments are yearly. I'll wait for Commerce 3 to be released

**Comment by andris-sevcenko** [comment]
This has been re-scheduled. Instead of aiming that for Commerce 3, we'll be doing Commerce 2.2 hopefully next week with the subscription billing issue support as the main feature. That will be paired with a release of Stripe for Commerce 2.2 (https://github.com/craftcms/commerce-stripe/tree/2.2)

**Comment by bymayo** [comment]
Thats really good news! I'll keep a look out on the 'Updates' section of our clients site next week then :)

**Comment by totov** [comment]
@andris-sevcenko thanks for all the information above, is there any update on the new version being rolled out?

**Comment by andris-sevcenko** [comment]
@totov when we get to it. We have to test it internally and we hope to get to that part soon.

**Comment by totov** [comment]
@andris-sevcenko is there any update on this?

**Comment by thisisjamessmith** [comment]
@andris-sevcenko What are the implications of this? Does it mean certain people won't be able to purchase subscriptions due to their card provider requiring 3DS authentication?

I've tried testing my subscription checkout with Stripe's 3DS testing cards (e.g. `4000000000003220`) and the transaction always fails. Am I doing something wrong or is this a Commerce/Commerce-Stripe bug?

**Comment by lukeholder** [comment]
@totov @bymayo this will fixed in Commerce 2.2 and Stripe Plugin 2.2

**Comment by thisisjamessmith** [comment]
@lukeholder This is still an issue for me with the latest versions of everything. I get the same error response when attempting to purchase a subscription using Stripe's `4000000000003220` card.

**Comment by thisisjamessmith** [comment]
@andris-sevcenko @lukeholder Should I create this a new issue? Are you able to replicate the problem? I'm outputting the Stripe checkout with the default `getPaymentFormHtml()` method, so nothing unusual there.
